import { existsSync, readdirSync, readFileSync, realpathSync } from "node:fs";
import path from "node:path";
import { CACHE_DIR, CONTEXT_DIR, type RepoConfig, type TargetTool } from "./config.ts";
import { warning, type Diagnostic } from "./diagnostics.ts";
import type { FactReport } from "./facts.ts";
import type { ResolvedRule, RuleSet } from "./compose.ts";
import { formatJson, isFile, toPosix } from "./util.ts";

export const BLOCK_BEGIN = "<!-- de-web-sdk:begin -->";
export const BLOCK_END = "<!-- de-web-sdk:end -->";
export const IGNORE_BEGIN = "# de-web-sdk:begin (generated by `de-web-sdk sync`; don't edit inside this block)";
export const IGNORE_END = "# de-web-sdk:end";
/** Every generated file carries this marker, so `sync` can find and remove its own files. */
export const GENERATOR_MARK = "Generated by de-web-sdk sync";
const NOTICE = `${GENERATOR_MARK}. Don't edit; run \`npx --no de-web-sdk sync\` to update.`;
const CLI = "npx --no de-web-sdk";

/**
 * Skill folders the SDK may write to. Claude Code reads only `.claude/skills/`,
 * and VS Code's Copilot reads `.claude/skills/`, `.github/skills/`, and
 * `.agents/skills/`, so one folder serves both tools and no tool sees a skill
 * twice.
 */
export const SKILL_DIRS: Record<TargetTool, string> = {
  "claude-code": ".claude/skills",
  "github-copilot": ".github/skills",
};
/** Earlier versions wrote Copilot's path-scoped instructions here. `sync` removes them. */
const COPILOT_INSTRUCTIONS_DIR = ".github/instructions";
const COPILOT_PREFIX = "de-web-sdk-";
/** Claude Code reads AGENTS.md only when neither of these exists. */
const CLAUDE_FILES = ["CLAUDE.md", ".claude/CLAUDE.md"];

export interface PlannedFile {
  path: string;
  content: string;
  /** Committed entry points; `check` warns when they're stale. */
  committed: boolean;
}

export interface AgentPlan {
  files: PlannedFile[];
  deletes: string[];
  warnings: Diagnostic[];
}

function rel(root: string, abs: string): string {
  return toPosix(path.relative(root, abs));
}

function readQuiet(abs: string): string | undefined {
  try {
    return readFileSync(abs, "utf8");
  } catch {
    return undefined;
  }
}

/** Replaces the managed block in `existing`, or appends one. Content outside the block is kept byte for byte. */
export function replaceBlock(existing: string | undefined, block: string, begin = BLOCK_BEGIN, end = BLOCK_END): string {
  if (existing === undefined || existing === "") return `${block}\n`;
  const start = existing.indexOf(begin);
  const stop = start === -1 ? -1 : existing.indexOf(end, start);
  if (start !== -1 && stop !== -1) return existing.slice(0, start) + block + existing.slice(stop + end.length);
  const sep = existing.endsWith("\n") ? "\n" : "\n\n";
  return `${existing}${sep}${block}\n`;
}

/** Removes the managed block. Returns undefined when nothing else remains. */
export function removeBlock(existing: string, begin = BLOCK_BEGIN, end = BLOCK_END): string | undefined {
  const start = existing.indexOf(begin);
  const stop = start === -1 ? -1 : existing.indexOf(end, start);
  if (start === -1 || stop === -1) return existing;
  const rest = (existing.slice(0, start) + existing.slice(stop + end.length).replace(/^\n/, "")).replace(/\n\n$/, "\n");
  return rest.trim() === "" ? undefined : rest;
}

export function extractBlock(existing: string | undefined, begin = BLOCK_BEGIN, end = BLOCK_END): string | undefined {
  if (!existing) return undefined;
  const start = existing.indexOf(begin);
  const stop = start === -1 ? -1 : existing.indexOf(end, start);
  return start === -1 || stop === -1 ? undefined : existing.slice(start, stop + end.length);
}

function flags(rule: ResolvedRule): string {
  return [rule.enforcement, rule.locked ? "locked" : undefined].filter(Boolean).join(", ");
}

function ruleLine(rule: ResolvedRule): string {
  const title = oneLine(rule.title);
  if (!rule.paths?.length) return `- \`${rule.ref}\` [${flags(rule)}]: ${title}`;
  const stop = /[.!?]$/.test(title) ? "" : ".";
  return `- \`${rule.ref}\` [${flags(rule)}]: ${title}${stop} Applies to ${rule.paths.map((p) => `\`${p}\``).join(", ")}.`;
}

function oneLine(text: string): string {
  const flat = text.replace(/\s+/g, " ").trim();
  return flat.length > 160 ? `${flat.slice(0, 157)}...` : flat;
}

/** The AGENTS.md block: every applicable rule and skill, the SDK's tools and commands, and pack commands, within the line budget. */
export function agentsBlock(set: RuleSet, config: RepoConfig): string {
  const head = [
    BLOCK_BEGIN,
    `<!-- ${NOTICE} -->`,
    "## Rules from agent packs",
    "",
    `Use the \`${MCP_SERVER_NAME}\` MCP server's tools when your agent has them. Otherwise run the command in parentheses.`,
    `- Before editing, call \`resolve\` (\`${CLI} resolve <files>\`) for the rules, skills, docs, and commands that apply.`,
    `- Before finishing, build if a rule reads build output, then call \`check\` (\`${CLI} check [files]\`). Apply each fix and rerun until it exits with 0.`,
    `- Load a skill with \`get_skill\` (\`${CLI} skill <name>\`). Don't read skill files from \`node_modules\` directly.`,
    `- If a rule looks wrong, call \`draft_feedback\` (\`${CLI} feedback <rule> --kind false-positive --message "<reason>"\`). Review the draft with the developer when they're present, then call \`submit_feedback\` (add \`--submit --yes\`).`,
    "",
  ];
  const tail = ["", `Rule detail and skills stay in the installed packs, and the SDK verifies them each time it serves them.`, BLOCK_END];

  const ruleLines = set.rules.length === 0 ? ["No pack rules apply to this repo yet."] : ["Rules:", ...set.rules.map((r) => ruleLine(r))];
  const skillLines = set.skills.length ? ["", "Skills (load with `get_skill`):", ...set.skills.map((s) => `- \`${s.installName}\`: ${oneLine(s.description || `The ${s.name} skill from ${s.pack}.`)}`)] : [];
  const skillShort = set.skills.length ? ["", `Skills: ${set.skills.length} available. \`resolve\` lists them, and \`get_skill\` loads one.`] : [];
  const commandLines = set.commands.length ? ["", "Pack commands:", ...set.commands.map((c) => `- \`${c.run}\`: ${oneLine(c.use)}`)] : [];
  const commandShort = set.commands.length ? ["", `Pack commands: ${set.commands.length}. \`resolve\` lists them.`] : [];

  const budget = config.agentsBlockLines;
  const fits = (body: string[]) => head.length + body.length + tail.length <= budget;
  for (const body of [
    [...ruleLines, ...skillLines, ...commandLines],
    [...ruleLines, ...skillShort, ...commandLines],
    [...ruleLines, ...skillShort, ...commandShort],
  ]) {
    if (fits(body)) return [...head, ...body, ...tail].join("\n");
  }

  // Over budget: point to rule groups per pack instead of listing rules.
  const byPack = new Map<string, ResolvedRule[]>();
  for (const r of set.rules) byPack.set(r.pack, [...(byPack.get(r.pack) ?? []), r]);
  const grouped = ["Rules, grouped by pack (the list is too long for this block):"];
  const packLines = [...byPack.entries()].map(([pack, rules]) => {
    const locked = rules.filter((r) => r.locked).length;
    return `- \`${pack}\`: ${rules.length} rule${rules.length === 1 ? "" : "s"}${locked ? `, ${locked} locked` : ""}. Call \`resolve\` with pack ${pack} (\`${CLI} resolve --pack ${pack}\`).`;
  });
  const rest = [...skillShort, ...commandShort];
  const room = budget - head.length - tail.length - grouped.length - rest.length;
  let shown = packLines;
  if (packLines.length > room) {
    shown = packLines.slice(0, Math.max(0, room - 1));
    shown.push(`- ${packLines.length - shown.length} more packs. \`resolve\` returns all rules.`);
  }
  return [...head, ...grouped, ...shown, ...rest, ...tail].join("\n");
}

export function claudeBlock(): string {
  return [BLOCK_BEGIN, `<!-- ${NOTICE} -->`, "@AGENTS.md", BLOCK_END].join("\n");
}

export const MCP_CONFIG = ".mcp.json";
export const MCP_SERVER_NAME = "de-web-sdk";
/**
 * The server entry `sync` keeps in `.mcp.json`, which Claude Code and VS Code
 * both read. It runs Node.js directly on the installed CLI, so it works on
 * every platform and never fetches a package from a registry.
 */
export const MCP_ENTRY = { type: "stdio", command: "node", args: ["node_modules/@de-web-sdk/cli/bin/de-web-sdk.js", "mcp"] };

/** Plans the managed server entry in `.mcp.json`, keeping every other server. */
export function planMcpConfig(root: string, config: RepoConfig): { file?: PlannedFile; delete?: boolean; warnings: Diagnostic[] } {
  const warnings: Diagnostic[] = [];
  const existing = readQuiet(path.join(root, MCP_CONFIG));
  let data: Record<string, unknown> = {};
  if (existing !== undefined) {
    try {
      data = JSON.parse(existing) as Record<string, unknown>;
    } catch {
      warnings.push(warning("mcp.configInvalid", `${MCP_CONFIG} isn't valid JSON, so sync left it unchanged. Fix it, then run sync`, { file: MCP_CONFIG }));
      return { warnings };
    }
  }
  const servers = { ...((data.mcpServers as Record<string, unknown> | undefined) ?? {}) };
  if (config.mcpServer) {
    servers[MCP_SERVER_NAME] = MCP_ENTRY;
    if (!isFile(path.join(root, ...MCP_ENTRY.args[0]!.split("/")))) {
      warnings.push(warning("mcp.cliMissing", `Agents start the MCP server from ${MCP_ENTRY.args[0]}, which isn't installed. Add @de-web-sdk/cli as a dev dependency`, { file: MCP_CONFIG }));
    }
  } else {
    if (!(MCP_SERVER_NAME in servers)) return { warnings };
    delete servers[MCP_SERVER_NAME];
    const others = Object.keys(data).filter((k) => k !== "mcpServers");
    if (Object.keys(servers).length === 0 && others.length === 0) return { delete: true, warnings };
  }
  const next = { ...data, mcpServers: servers };
  return { file: { path: MCP_CONFIG, content: formatJson(next), committed: true }, warnings };
}

/** True when the text outside our block already imports AGENTS.md. */
export function importsAgentsMd(text: string): boolean {
  return /^[ \t]*@(\.\/)?AGENTS\.md[ \t]*$/m.test(text);
}

function yamlString(text: string): string {
  return JSON.stringify(text.replace(/\s+/g, " ").trim());
}



/** The generated index of rule detail, skills, and docs in their installed packages. Not committed. */
export function contextIndex(root: string, set: RuleSet, report: FactReport): string {
  const lines = [`<!-- ${NOTICE} -->`, "# Agent pack context", "", "## Facts", ""];
  const f = report.facts;
  lines.push(`- Bundler: ${f.bundler}${f.bundlerVersion ? ` ${f.bundlerVersion}` : ""}`);
  lines.push(`- Module Federation: ${f.moduleFederation}`);
  lines.push(`- Role: ${f.role}`);
  if (f.react) lines.push(`- React: ${f.react}`);
  lines.push("", "## Rules", "");
  for (const r of set.rules) {
    lines.push(`- \`${r.ref}\` [${flags(r)}]: ${oneLine(r.title)}${r.guidance ? ` Guidance: \`${r.guidance.display}\`.` : ""}`);
  }
  if (set.skills.length) {
    lines.push("", "## Skills", "");
    for (const s of set.skills) lines.push(`- \`${s.installName}\`: ${oneLine(s.description)} Load it with \`get_skill\` or \`${CLI} skill ${s.installName}\`.`);
  }
  if (set.docs.length) {
    lines.push("", "## Reference docs", "");
    for (const d of set.docs) lines.push(`- ${d.title} (${d.pack}): \`${d.display}\`${d.description ? `. ${oneLine(d.description)}` : ""}`);
  }
  if (set.commands.length) {
    lines.push("", "## Commands", "");
    for (const c of set.commands) lines.push(`- \`${c.run}\` (${c.pack}): ${oneLine(c.use)}`);
  }
  return `${lines.join("\n")}\n`;
}

function isGenerated(abs: string): boolean {
  return (readQuiet(abs) ?? "").includes(GENERATOR_MARK);
}

function listDirs(abs: string): string[] {
  try {
    return readdirSync(abs, { withFileTypes: true })
      .filter((d) => d.isDirectory() || d.isSymbolicLink())
      .map((d) => d.name)
      .sort();
  } catch {
    return [];
  }
}


/**
 * Plans every file `sync` generates. Nothing is written here, so a trust
 * failure elsewhere leaves existing files untouched.
 */
export function planAgentFiles(root: string, set: RuleSet, config: RepoConfig, report: FactReport): AgentPlan {
  const files: PlannedFile[] = [];
  const deletes: string[] = [];
  const warnings: Diagnostic[] = [];
  const ignored = [`/${CONTEXT_DIR}/`, `/${CACHE_DIR}/`];

  files.push({ path: "AGENTS.md", content: replaceBlock(readQuiet(path.join(root, "AGENTS.md")), agentsBlock(set, config)), committed: true });

  // AGENTS.md is the one committed entry point. Claude Code reads it natively
  // unless the repo has a CLAUDE.md, so an existing CLAUDE.md gets an import.
  for (const rel of CLAUDE_FILES) {
    const existing = readQuiet(path.join(root, rel));
    if (existing === undefined) continue;
    const outside = removeBlock(existing) ?? "";
    const wantImport = config.targets.includes("claude-code") && outside.trim() !== "" && !importsAgentsMd(outside);
    if (wantImport) files.push({ path: rel, content: replaceBlock(existing, claudeBlock()), committed: true });
    else if (extractBlock(existing)) {
      // Our block is no longer needed: the file imports AGENTS.md itself, holds
      // nothing else, or Claude Code isn't a target.
      if (outside.trim() === "") deletes.push(rel);
      else files.push({ path: rel, content: outside, committed: true });
    }
  }

  const instructionsDir = path.join(root, COPILOT_INSTRUCTIONS_DIR);
  if (existsSync(instructionsDir)) {
    for (const name of readdirSync(instructionsDir).sort()) {
      const p = `${COPILOT_INSTRUCTIONS_DIR}/${name}`;
      if (name.startsWith(COPILOT_PREFIX) && isGenerated(path.join(root, p))) deletes.push(p);
    }
  }

  // Skills are served by the SDK, so no skill files are installed. Remove any an earlier version generated.
  for (const toolDir of Object.values(SKILL_DIRS)) {
    for (const name of listDirs(path.join(root, toolDir))) {
      const file = `${toolDir}/${name}/SKILL.md`;
      if (isGenerated(path.join(root, file))) deletes.push(file);
    }
  }

  const mcp = planMcpConfig(root, config);
  if (mcp.file) files.push(mcp.file);
  if (mcp.delete) deletes.push(MCP_CONFIG);
  warnings.push(...mcp.warnings);

  files.push({ path: `${CONTEXT_DIR}/index.md`, content: contextIndex(root, set, report), committed: false });

  const gitignore = [IGNORE_BEGIN, ...ignored, IGNORE_END].join("\n");
  files.push({ path: ".gitignore", content: replaceBlock(readQuiet(path.join(root, ".gitignore")), gitignore, IGNORE_BEGIN, IGNORE_END), committed: true });

  return { files, deletes: [...new Set(deletes)].sort(), warnings };
}

/** Committed entry points that differ from what `sync` would write. */
export function staleEntryPoints(root: string, plan: AgentPlan): string[] {
  const stale: string[] = [];
  for (const f of plan.files) {
    if (!f.committed) continue;
    if (readQuiet(path.join(root, f.path)) !== f.content) stale.push(f.path);
  }
  for (const d of plan.deletes) if (!d.includes("/skills/")) stale.push(d);
  return stale.sort();
}
